#page title
page_title                                : Countdowns

# App Info
ios_app_id                                : 917514700

appstore_link                             : https://apps.apple.com/app/apple-store/id917514700?pt=487792&ct=ShareLink&mt=8

presskit_download_link                    : assets/Countdowns_Press_Kit.zip

app_icon                                  : assets/appicon.png
app_name                                  : Countdowns
app_price                                 : Free
app_description                           : Countdowns is an app for iOS & macOS designed to help you count down to those important moments in life. Perfect for birthdays, holidays, weddings, anniversaries, vacations, retirement, and other special events!

enable_smart_app_banner                   : true



# Information About Yourself
your_name                                 : Shayes Apps LLC
your_link                                 : https://shayesapps.com                              
email_address                             : support@shayesapps.com
facebook_username                         : shayesapps                                          
twitter_username                          : shayesapps



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Unlimited Countdowns
    description                           : Unlimited countdowns which can count up or down
    fontawesome_icon_name                 : clock
    
  - title                                 : Widgets
    description                           : See countdowns right on your home screen
    fontawesome_icon_name                 : th-large

  - title                                 : Customizable Units
    description                           : Pick the units you want for each individual countdown
    fontawesome_icon_name                 : cog

  - title                                 : Recurring Events
    description                           : Track recurring events like birthdays, anniversaries, and more
    fontawesome_icon_name                 : redo

  - title                                 : Calendar Integration
    description                           : Import events directly from your calendar
    fontawesome_icon_name                 : calendar-alt
  
  - title                                 : iCloud Sync
    description                           : Sync countdowns and lists between all your devices
    fontawesome_icon_name                 : cloud

  - title                                 : Notifications
    description                           : Choose when to be notified before each countdown
    fontawesome_icon_name                 : dot-circle

  - title                                 : Lists
    description                           : Create your own lists to categorize your countdowns
    fontawesome_icon_name                 : list-ul

  - title                                 : Archive
    description                           : Keep and view past countdowns
    fontawesome_icon_name                 : archive

  - title                                 : Siri Integration
    description                           : Check on your countdowns with just your voice
    fontawesome_icon_name                 : magic

  - title                                 : Apple Watch
    description                           : Support for Apple Watch & Complications
    fontawesome_icon_name                 : star

  - title                                 : Localized
    description                           : Available in 15+ languages
    fontawesome_icon_name                 : globe



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_overlay_color_1                     : "#142630"
cover_overlay_color_2                     : "#243b55"

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
